---
# ansible-playbook nginx_controller_agent.yaml -i loadbalancers -e "admin_email=user@company.com admin_password=userPassword" 
# ansible-playbook nginx_controller_agent_3x.yaml -e "@nginx_install_controller_vars.yaml"

- hosts: loadbalancers
  remote_user: ubuntu
  become: true
  become_method: sudo
  gather_facts: yes

  tasks:
  - name: install minimal support for python2 for Agent install script
    apt:
      name: "{{ packages }}"
      state: present
    vars:
      packages:
      - python-minimal
      - libxerces-c3.2

  - include_role:
      name: nginx_controller_generate_token

  - name: Get controller api key for agent registration
    uri:
      url: "https://{{controller_fqdn}}/api/v1/platform/global"
      method: "GET"
      return_content: yes
      status_code: 200
      validate_certs: false
      headers:
        Cookie: "{{controller_auth_token}}"
    register: ctrl_globals

  - name: Copy api_key to a variable
    set_fact:
      api_key: "{{ctrl_globals.json.currentStatus.agentSettings.apiKey}}"

  - name: install the agent
    include_role:
      name: nginx_controller_agent
