---
# # for some reason this does not work with the Jinja template
- hosts: localhost

  tasks:
- hosts: loadbalancers
  remote_user: ubuntu
  become: true

  pre_tasks:
  - name: load the vars
    include_vars: 
      file: "{{playbook_dir}}/nginx_plus_vars.yaml"

  roles:
    - nginx


